#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        0
bspc config window_gap          5
bspc config top_padding		30
bspc config bottom_padding	10
bspc config left_padding	10
bspc config right_padding	10



bspc config split_ratio 		0.50
bspc config borderless_monocle          true
bspc config gapless_monocle      	true
bspc config single_monocle	 	true
bspc config pointer_follows_focus 	true
bspc config focus_follows_pointer 	true



bspc rule -a Gimp desktop='^8' state=tiling follow=on



setxkbmap tr &
picom --experimental-backends &
nitrogen --restore &
polybar &
pulseaudio &
