#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X
#Dual monitor
#find out names with arandr or xrandr
#bspc monitor DP-2 -d 1 2 3 4 5 6 7 8 9
#bspc monitor LVDS1 -d 1 2 3 4
#bspc monitor DP3 -d  5 6 7 8 9
#bspc monitor HDMI-A-0 -d 1 2 3 4 5 6 7 8 9 10
#bspc monitor HDMI-1 -d 1 2 3 4 5 6 7 8 9 10
#bspc monitor HDMI1 -d 1 2 3 4 5
#bspc monitor HDMI2 -d 6 7 8 9 10



bspc config border_width        3
bspc config window_gap          5
bspc config top_padding		10
bspc config bottom_padding	10
bspc config left_padding	10
bspc config right_padding	10



bspc config focused_border_color \#F2CDCD 	
bspc config normal_border_color \#F28FAD



bspc config split_ratio 		0.50
bspc config borderless_monocle          true
bspc config gapless_monocle      	true
#bspc config single_monocle	 	true
bspc config pointer_follows_focus 	true
bspc config focus_follows_pointer 	true



#bspc rule -a Gimp desktop='^8' state=tiling follow=on



setxkbmap tr &
picom --experimental-backends &
nitrogen --restore &
xsetroot -cursor_name left_ptr &
gamma &
